services:
  - type: web
    name: crimznbot-site
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: OPENAI_API_KEY
        sync: false
