github.com:
    users:
        MUSICNFTACCESS:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: MUSICNFTACCESS
